%% RUN_AEB_EXAMPLE
% Small MATLAB re-simulation of the synthetic AEB decision chain.

clear;
clc;

% Synthetic test inputs
distance_m = [30 25 20 15 12 10];
vehicle_speed_kmh = [40 40 40 40 40 40];
relative_closing_speed_ms = vehicle_speed_kmh ./ 3.6;

pedestrian_detected = true(size(distance_m));
pedestrian_in_path = [false false true true true true];

% Physics
ttc_seconds = calculate_ttc( ...
    distance_m, ...
    relative_closing_speed_ms);

% ADAS decisions
fcw = determine_fcw_trigger( ...
    pedestrian_detected, ...
    pedestrian_in_path, ...
    ttc_seconds);

aeb = determine_aeb_trigger( ...
    pedestrian_detected, ...
    pedestrian_in_path, ...
    ttc_seconds);

% Display
results = table( ...
    distance_m(:), ...
    vehicle_speed_kmh(:), ...
    ttc_seconds(:), ...
    pedestrian_in_path(:), ...
    fcw(:), ...
    aeb(:), ...
    'VariableNames', { ...
        'Distance_m', ...
        'Speed_kmh', ...
        'TTC_s', ...
        'InPath', ...
        'FCW', ...
        'AEB'});

disp(results);

% Plot TTC and synthetic thresholds
figure;
plot(1:numel(ttc_seconds), ttc_seconds, "-o");
hold on;
yline(2.5, "--", "FCW threshold");
yline(1.5, "--", "AEB threshold");
xlabel("Sample");
ylabel("TTC (s)");
title("Synthetic AEB/FCW TTC Re-simulation");
grid on;
hold off;
