"""
Scenario-level ADAS performance KPI analysis.

This module calculates engineering KPIs from simulated
ADAS telemetry and independent ground-truth signals.

All metrics are based on the synthetic project model.
They are not official OEM, Euro NCAP, UNECE, or regulatory metrics.
"""

from __future__ import annotations

import numpy as np
import pandas as pd

from src.validation import calculate_binary_metrics


def calculate_scenario_kpis(
    telemetry: pd.DataFrame,
) -> dict[str, float | int | str | bool]:
    """
    Calculate scenario-level ADAS performance KPIs.

    Parameters
    ----------
    telemetry:
        Telemetry DataFrame generated by
        generate_scenario_telemetry().

    Returns
    -------
    dict
        Scenario-level performance KPIs.
    """

    # -------------------------------------------------------------
    # 1. Validate required columns
    # -------------------------------------------------------------

    required_columns = {
        "scenario_id",
        "ttc_seconds",
        "pedestrian_detected",
        "warning_triggered",
        "brake_triggered",
        "ground_truth_warning_required",
        "ground_truth_braking_required",
    }

    missing_columns = required_columns - set(telemetry.columns)

    if missing_columns:
        raise ValueError(
            f"Missing required telemetry columns: "
            f"{sorted(missing_columns)}"
        )

    if telemetry.empty:
        raise ValueError("Telemetry DataFrame cannot be empty.")

    # -------------------------------------------------------------
    # 2. Scenario identification
    # -------------------------------------------------------------

    scenario_id = str(telemetry["scenario_id"].iloc[0])

    # -------------------------------------------------------------
    # 3. Basic scenario KPIs
    # -------------------------------------------------------------

    min_ttc = telemetry["ttc_seconds"].min()

    detection_rate = telemetry["pedestrian_detected"].mean()

    warning_count = int(
        telemetry["warning_triggered"].sum()
    )

    brake_count = int(
        telemetry["brake_triggered"].sum()
    )

    # -------------------------------------------------------------
    # 4. Ground-truth event exposure
    # -------------------------------------------------------------

    gt_warning_events = int(
        telemetry["ground_truth_warning_required"].sum()
    )

    gt_braking_events = int(
        telemetry["ground_truth_braking_required"].sum()
    )

    fcw_exercised = gt_warning_events > 0

    aeb_exercised = gt_braking_events > 0

    # -------------------------------------------------------------
    # 5. FCW validation
    # -------------------------------------------------------------

    if fcw_exercised:

        fcw_metrics = calculate_binary_metrics(
            telemetry["ground_truth_warning_required"].to_numpy(),
            telemetry["warning_triggered"].to_numpy(),
        )

        fcw_precision = fcw_metrics["precision"]
        fcw_recall = fcw_metrics["recall"]
        fcw_f1 = fcw_metrics["f1"]

    else:

        fcw_precision = np.nan
        fcw_recall = np.nan
        fcw_f1 = np.nan

    # -------------------------------------------------------------
    # 6. AEB validation
    # -------------------------------------------------------------

    ground_truth_aeb = telemetry[
        "ground_truth_braking_required"
    ].to_numpy(dtype=bool)

    predicted_aeb = telemetry[
        "brake_triggered"
    ].to_numpy(dtype=bool)

    true_positive = int(
        np.sum(ground_truth_aeb & predicted_aeb)
    )

    false_positive = int(
        np.sum(~ground_truth_aeb & predicted_aeb)
    )

    false_negative = int(
        np.sum(ground_truth_aeb & ~predicted_aeb)
    )

    true_negative = int(
        np.sum(~ground_truth_aeb & ~predicted_aeb)
    )

    if aeb_exercised:

        aeb_metrics = calculate_binary_metrics(
            ground_truth_aeb,
            predicted_aeb,
        )

        aeb_precision = aeb_metrics["precision"]
        aeb_recall = aeb_metrics["recall"]
        aeb_f1 = aeb_metrics["f1"]

    else:

        aeb_precision = np.nan
        aeb_recall = np.nan
        aeb_f1 = np.nan

    # -------------------------------------------------------------
    # 7. Return KPI summary
    # -------------------------------------------------------------

    return {
        "scenario_id": scenario_id,

        "min_ttc_s": (
            float(min_ttc)
            if np.isfinite(min_ttc)
            else np.nan
        ),

        "detection_rate": float(detection_rate),

        "gt_warning_events": gt_warning_events,
        "gt_braking_events": gt_braking_events,

        "fcw_exercised": fcw_exercised,
        "aeb_exercised": aeb_exercised,

        "warning_count": warning_count,
        "brake_count": brake_count,

        "aeb_tp": true_positive,
        "aeb_tn": true_negative,
        "aeb_fp": false_positive,
        "aeb_fn": false_negative,

        "fcw_precision": fcw_precision,
        "fcw_recall": fcw_recall,
        "fcw_f1": fcw_f1,

        "aeb_precision": aeb_precision,
        "aeb_recall": aeb_recall,
        "aeb_f1": aeb_f1,
    }